### ISSUE TITLE
[BUG] RTL Widgets looks wrong

### ISSUE THREAD

**Issue by jacobel640** [Smooth-E/wireless-adb-switch#29] opened 2024-08-18 08:06 UTC
# System information

> Describe your setup, so we can understand the cause of the bug better

- Android version: Android 11
- Android vendor: AOSP
- Mode: root & Shizuku
- WADBS version: 1.2
- Where did you get the app from: GitHub
- Any additional information you would like to share about your system - none

# The home screen Widgets round corners are weird probably RTL related problem 

> Lawnchair 12
![Screenshot_20240818-105811~2](https://github.com/user-attachments/assets/0c6adbb4-7bc6-41fe-8ed3-0f8a9f5de6ff)

- [v ] This issue was not reported before
- [v ] I agree to keep the discussion polite and on point

**Comment by Smooth-E** [comment] 2024-11-03 01:57
Hello! Thanks a lot for reporting this issue and being interested in WADBS! The issue is now fixed, next release will land  after I resolve #32 and #30, probably

**Closed by Smooth-E** 2024-11-03 01:57 UTC
Labels: bug
